version: '3'

services:
    nginx:
            build:
                context: ./nginx
            volumes:
                - "../src:/var/www"
                - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
                - "./nginx/sites/:/etc/nginx/sites-available"
                - "./nginx/conf.d/:/etc/nginx/conf.d"
            ports:
                - "80:80"
                - "443:443"
    aspnetapp:
            build:
                context: ./aspNetCore
                dockerfile: Dockerfile
            expose:
                - "80"